import { getChapterContent, getChapterDetails } from "@/lib/data-loader";
import QuizPageClient from "@/components/quiz/QuizPageClient";

// This interface defines the shape of the RESOLVED params object
interface QuizPageParams {
  subjectSlug: string;
  paperSlug: string;
  chapterSlug: string;
}

// This interface matches the PageProps generated by Next.js
interface PageProps {
  params: Promise<QuizPageParams>;
}

// Use the correct PageProps interface
export default async function QuizPage({ params }: PageProps) {
  // CRUCIAL STEP: Await the params promise to get the actual data
  const resolvedParams = await params;

  // Use the resolvedParams object for your data fetching logic
  const { subjectSlug, paperSlug, chapterSlug } = resolvedParams;

  const [chapter, questions] = await Promise.all([
    getChapterDetails(subjectSlug, paperSlug, chapterSlug),
    getChapterContent(subjectSlug, paperSlug, chapterSlug, "quizzes"),
  ]);

  if (!chapter || !questions) {
    return <div>Quiz content not found.</div>;
  }

  return <QuizPageClient chapter={chapter} questions={questions} />;
}
