export const actions = {
  profile: {
    DATA_FETCHING: "PROFILE_DATA_FETCHING",
    PROFILE_DATA_FETCHED: "PROFILE_DATA_FETCHED",
    PROFILE_DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
    PROFILE_BIO_EDITED: "PROFILE_BIO_EDITED",
    IMAGE_UPDATED: "IMAGE_UPDATED",
    TOGGLE_BLOG_CONTENT_DISPLAY: "TOGGLE_BLOG_CONTENT_DISPLAY",

    DELETE_BLOG: 'DELETE_BLOG',
  },
  blogs: {
    FETCH_BLOGS_REQUEST: "FETCH_BLOGS_REQUEST",
    FETCH_BLOGS_SUCCESS: "FETCH_BLOGS_SUCCESS",
    FETCH_BLOGS_FAILURE: "FETCH_BLOGS_FAILURE",

    DATA_CREATED: "DATA_CREATED", // Corrected action type
    DATA_EDITED: "DATA_EDITED",
    POST_DELETED: "POST_DELETED",
  },
};
